### ISSUE TITLE
Proposal to remove a line #17

### ISSUE THREAD

**Issue by arbazkiraak** [ehsahil/gujjubang.github.io#1]
- [x] @ehsahil 

> Using a foul language for my friend "Daniel Bharatwasi" [At line 17](https://github.com/ehsahil/gujjubang.github.io/blob/master/index.html#L7) 

- violates our friendship rule & can't be tolerated. 

<i>A loyal friend laughs at your jokes when they’re not so good, and sympathizes with your problems when they’re not so bad.</i>
-Arnold H. Glasgow

<del><i> Every situation of boundary-violation is different, and the who of who is involved is a very important piece of information we need for us to make the best decision of our wellbeing.</i></del>

**Comment by ehsahil** [comment]
fixed.
